### ISSUE TITLE
Suspected bug in dictresize

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1168]
I've now seen a handful of cases when I get a segfault in dictresize. I haven't been able to reproduce it with a small program (only a gargantuan one with external dependencies etc). I am fiddling with GC settings and have a large heap (20G), a guess could be something like:
- dictresize is triggered by the dict being too big
- dictresize starts working and does malloc
- malloc is when GC gets to run and it decides to run
- GC cleans stuff up
- dictresize tries to access stuff that was cleaned up? but how? not a direct pointer but some offset or whatnot so the GC didn't see it?

perhaps we can just stare a bit at the dictresize code and try to figure things out? :)  Here's a backtrace:

```
Thread 4 (Thread 0x7f8c8171c6c0 (LWP 397947) "Worker 2"):
#0  0x00007f9182819ac7 in __GI___wait4 (pid=398811, stat_loc=stat_loc@entry=0x0, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
        sc_ret = -512
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f9182819a47 in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ./posix/waitpid.c:38
No locals.
#2  0x00000000002cf09b in print_trace () at rts/rts.c:2010
        pid_buf = "\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\b\000\000\000\000\000\220\037x\202\221\177"
        name_buf = "\a", '\000' <repeats 23 times>, "\002", '\000' <repeats 15 times>, "\001\000\000\000\000\000\000\000u\000\000\000\000\000\000\000f\252q\201\214\177\000\000\227\002\000\000\000\000\000\000UU\005\000\000\000\000\000\252\252\002\000\000\000\000\000\000\000 \000\000\000\000\000\000p\302\000\220\177", '\000' <repeats 20 times>, "\b", '\000' <repeats 29 times>, "\vv\200b\000\000\000\000\200\262q\201\214\177\000\000B\357-\000\000\000\000\000\002\002\001\000\000\000\000\000\063\000\000\000\000\000+\000\006\000\000\000\000\000\000\000"...
        child_pid = -512
#3  0x00000000002cf1ea in sigillsegv_handler (signum=11) at rts/rts.c:2024
No locals.
#4  <signal handler called>
No locals.
#5  dictresize (d=d@entry=0x7f8d2a804500) at builtin/dict_impl.c:194
        numelements = 174762
        oldtable = 0x7f9000c27000
        minsize = <optimized out>
        newsize = <optimized out>
        newtable = 0x0
        oldentries = <optimized out>
        newentries = <optimized out>
#6  0x00000000002d3090 in insertdict (dict=0x7f8d2a804500, hashwit=0x7f8c8275f4b0, hash=174776, key=0x7f8f97b2ede0, value=0x7f8e32204b40) at builtin/dict_impl.c:289
        hashpos = <optimized out>
        ix = <optimized out>
        old_value = <optimized out>
        table = <optimized out>
        ep = <optimized out>
        hashpos = <optimized out>
#7  $dict_setitem (dict=0x7f8d2a804500, hashwit=0x7f8c8275f4b0, key=0x7f8f97b2ede0, value=0x7f8e32204b40) at builtin/dict_impl.c:370
        hash = 174776
#8  0x00000000004a8799 in nsoapi$schema$$SchemaBuilder$_on_ns_elem (self=0x7f8c82750e00, c$cont=0x7f8fcffaf600, elem=0x7f8d5ecc0e20) at acton-streamer/out/types/nsoapi/schema.c:3247
        node = 0x7f8e32204b40
        etype = 0x7f8d5ec60440
        _etype = 0x7f8d5ec60380
        t = 0x7f8d5ec59f00
        w$5492 = 0x7f8d5a3579a0
        w$5646 = 0x7f8d5a357900
        w$5610 = 0x7f8f962daae0
        w$5588 = 0x7f8f962daa80
        w$5566 = 0x7f8f962daa20
        w$5543 = 0x7f8f962da900
        w$5828 = 0x7f8fcffaf5c0
        w$5525 = 0x7f8ec6a5b6f0
#9  0x000000000045cb0d in nsoapi$schema$$l$2proc$__call__ (p$self=0x7f8d5a234140, p$1=0x7f8fcffaf600, p$2=0x7f8d5ecc0e20) at acton-streamer/out/types/nsoapi/schema.c:41
        l$1obj = 0x7f8c82750e00
#10 0x000000000045cbfc in nsoapi$schema$$l$2proc$__exec__ (p$self=0x7f8d5a234140, p$1=0x7f8fcffaf600, p$2=0x7f8d5ecc0e20) at acton-streamer/out/types/nsoapi/schema.c:44
No locals.
#11 0x000000000045fdd4 in nsoapi$schema$$l$10c$7cont (e=0x7f8d5ecc0e20, n$16val=0x7f8d5ecc0e20, n$15iter=0x7f8d5a2340a0, w$5416=0x7f8ec68ade00, c$cont=0x4ffba0 <$Done$instance>, on_elem=0x7f8d5a234140, c$8res=0x0) at acton-streamer/out/types/nsoapi/schema.c:237
No locals.
#12 0x0000000000460373 in nsoapi$schema$$l$14Cont$__call__ (p$self=0x7f8fcffaf640, p$1=0x0) at acton-streamer/out/types/nsoapi/schema.c:255
        e = 0x7f8d5ecc0e20
        n$16val = 0x7f8d5ecc0e20
        n$15iter = 0x7f8d5a2340a0
        w$5416 = 0x7f8ec68ade00
        c$cont = 0x4ffba0 <$Done$instance>
        on_elem = 0x7f8d5a234140
#13 0x00000000002c909c in wt_work_cb (ev=<optimized out>) at rts/rts.c:1448
        current = 0x7f8c82750e00
        m = 0x7f8cbad951e0
        cont = 0x7f8fcffaf640
        val = 0x0
        r = {tag = $RCONT, cont = 0x7f8fcffaf640, value = 0x0}
        diff = <optimized out>
        ts_start = {tv_sec = 8068141, tv_nsec = 556528654}
        ts1 = {tv_sec = 8068141, tv_nsec = 557202560}
        ts2 = {tv_sec = 8068141, tv_nsec = 557202510}
        ts3 = {tv_sec = 8068141, tv_nsec = 557202530}
        wtid = <optimized out>
        runtime = <optimized out>
#14 0x000000000036640f in uv__run_check (loop=0x7f8c82723400) at src/unix/loop-watcher.c:67
        h = 0x51d830 <work_ev+240>
        queue = {0x7f8c8171bd20, 0x7f8c8171bd20}
        q = 0x51d898 <work_ev+344>
#15 0x0000000000356792 in uv_run (loop=0x7f8c82723400, mode=UV_RUN_DEFAULT) at src/unix/core.c:420
        timeout = -1
        r = 0
        can_sleep = 1
```

**Comment by plajjan** [comment]
I am able to reproduce this issue and although I cannot say with 100% certainty as I don't have the terminal left where I ran these tests, I do think that I have accidentally set GC_MAX_HEAP_SIZE and so we probably ran out of memory. I think it's pretty much OK to segfault at that point. Thus, I think the bug might be that malloc failures are not handled properly, not that we otherwise have memory corruption.

I don't think it's worthwhile looking in to this now. I think we should do exhaustive malloc-failure-testing at some point, but not now, so I'll close this.
