### ISSUE TITLE
SIGILL after exceptions

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1473]
Finn fem fel...

```
#0  0x0000000000ec0907 in acton_streamerQ_nsoapiQ_maapiQ_L_58C_36cont (error=0x10dc900 <$t>, has_more=0x0, self=0x7f2c57c9e840, C_cont=0x10ddca0 <$Done$instance>, 
    op=0x10dbde0 <B_int_strs+7424>, term_cb=0x7f2c4fc46820, finished_cb=0x7f2c4fc499c0, C_37res=0x0) at acton-streamer/out/types/acton_streamer/nsoapi/maapi.c:1704
No locals.
#1  0x0000000000ec237f in acton_streamerQ_nsoapiQ_maapiQ_L_64ContD___call__ (L_self=0x7f2c4fad5c80, G_1=0x0) at acton-streamer/out/types/acton_streamer/nsoapi/maapi.c:1785
        has_more = 0x10dc900 <$t>
        error = 0x0
        self = 0x7f2c57c9e840
        C_cont = 0x10ddca0 <$Done$instance>
        op = 0x10dbde0 <B_int_strs+7424>
        term_cb = 0x7f2c4fc46820
        finished_cb = 0x7f2c4fc499c0
#2  0x000000000047cd0d in wt_work_cb (ev=0x10ff908 <work_ev+120>) at base/rts/rts.c:1485
        diff = 752
        current = 0x7f2c57c9e840
        m = 0x7f2c4fad5050
        cont = 0x7f2c4fad5c80
        val = 0x0
        r = {tag = $RCONT, cont = 0x7f2c4fad5c80, value = 0x0}
        diff = 120
        jump0 = 0x7f2c57cb2e00
        wtid = 1
        ts_start = {tv_sec = 2098474, tv_nsec = 349787406}
        ts1 = {tv_sec = 2098474, tv_nsec = 351278983}
        ts2 = {tv_sec = 2098474, tv_nsec = 351278743}
        ts3 = {tv_sec = 2098474, tv_nsec = 351278863}
        runtime = 1491457
#3  0x00000000005747e2 in uv__run_check (loop=0x7f2c57c8f800) at src/unix/loop-watcher.c:67
        h = 0x10ff908 <work_ev+120>
        queue = {next = 0x7f2c5045cc48, prev = 0x7f2c5045cc48}
```

**Comment by nordlander** [comment]
PR #1474 should solve this problem. Looking at the generated code, the error causing the crash is now gone. But I haven't actually run the full example...

**Comment by plajjan** [comment]
I have now tested with the previously failing test cases and this does indeed fix the problem. Good job! Closing...
