### ISSUE TITLE
Segfault when multiple clients connect to listening socket

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#484]
I use examples/server to set up a TCP server listening on port 12345 and then connect two clients. The first goes well but when the second connects, the server dies with a segfault.

Running in gdb:
```
(gdb) run
Starting program: /home/kll/terastream/acton/examples/server 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7c13640 (LWP 1097051)]
[New Thread 0x7ffff7412640 (LWP 1097052)]
[New Thread 0x7ffff6c11640 (LWP 1097053)]
[New Thread 0x7ffff6410640 (LWP 1097054)]
[New Thread 0x7ffff5c0f640 (LWP 1097055)]
[New Thread 0x7ffff540e640 (LWP 1097056)]
[New Thread 0x7ffff4c0d640 (LWP 1097057)]
[New Thread 0x7fffeffff640 (LWP 1097058)]
[New Thread 0x7fffef7fe640 (LWP 1097059)]
[New Thread 0x7fffeeffd640 (LWP 1097060)]
[New Thread 0x7fffee7fc640 (LWP 1097061)]
[New Thread 0x7fffedffb640 (LWP 1097062)]
[New Thread 0x7fffed7fa640 (LWP 1097063)]
[New Thread 0x7fffecff9640 (LWP 1097064)]
[New Thread 0x7fffec7f8640 (LWP 1097065)]
[New Thread 0x7fffebff7640 (LWP 1097066)]
[New Thread 0x7fffeb7f6640 (LWP 1097067)]
[New Thread 0x7fffeaff5640 (LWP 1097068)]
[New Thread 0x7fffea7f4640 (LWP 1097069)]
[New Thread 0x7fffe9ff3640 (LWP 1097070)]
[New Thread 0x7fffe97f2640 (LWP 1097071)]
[New Thread 0x7fffe8ff1640 (LWP 1097072)]
[New Thread 0x7fffe87f0640 (LWP 1097073)]
[New Thread 0x7fffe7fef640 (LWP 1097074)]
[New Thread 0x7fffe77ee640 (LWP 1097075)]
[New Thread 0x7fffe6fed640 (LWP 1097076)]
[New Thread 0x7fffe67ec640 (LWP 1097077)]
[New Thread 0x7fffe5feb640 (LWP 1097078)]
[New Thread 0x7fffe57ea640 (LWP 1097079)]
[New Thread 0x7fffe4fe9640 (LWP 1097080)]
[New Thread 0x7fffe47e8640 (LWP 1097081)]
[New Thread 0x7fffe3fe7640 (LWP 1097082)]
[New Thread 0x7fffe37e6640 (LWP 1097083)]
Connection from localhost
Connection from localhost

Thread 5 "Worker 3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6410640 (LWP 1097054)]
0x000000000041f63e in ENQ_msg (m=0x7fffd4000bd0, a=0x7fffdc001a70) at rts/rts.c:522
522	        while (x->$next)
(gdb) bt
#0  0x000000000041f63e in ENQ_msg (m=0x7fffd4000bd0, a=0x7fffdc001a70) at rts/rts.c:522
#1  0x000000000041ffbe in FLUSH_outgoing (self=0x4ec990, txnid=0x0) at rts/rts.c:776
#2  0x0000000000422513 in main_loop (idx=0x3) at rts/rts.c:1225
#3  0x00007ffff7f2beae in start_thread (arg=0x7ffff6410640) at pthread_create.c:463
#4  0x00007ffff7d16a5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

If I run with `./server --rts-verbose --rts-debug` I haven't been able to reproduce it. Could it be timing related? Are we modifying x->$next outside of a lock?

**Comment by nordlander** [comment]
Does it always (often) fail at the same spot? If so I'd like to do a few gdb printouts after it has stopped:
    a->$class->$GCINFO
    a->$msg
    a->$msg->$next
    a->$msg->$next->...->$next     (until it becomes NULL)
It would also be interesting to know if any other threads are awake at this time, and where they are working if that's the case.

The error is very likely timing related, which is why I hope you'll be able to provide the above printouts next time it fails. All manipulation of the message queues are (meant to be) protected by spinlocks, which includes writing to the $next fields. But I'll do another scan of the code to see if this has been accidentally broken.
