### ISSUE TITLE
Investigate DB client_api assertion in send_packet_wait_replies_async

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#532]
While repeatedly running the TCP resume test I occasionally see assertion failures from the db_client lib:
```
...
Traceback (most recent call last):
  File "/home/kll/terastream/acton/test/./test_db.py", line 349, in test_app_tcp_recovery
    tcp_cmd(self.p, app_port, "INC")
  File "/home/kll/terastream/acton/test/./test_db.py", line 91, in tcp_cmd
    return tcp_cmd(p, port, cmd, retries-1)
  File "/home/kll/terastream/acton/test/./test_db.py", line 78, in tcp_cmd
    raise TcpCmdError(f"Process is dead, returncode: {p.returncode}  stdout: {p.stdout.read()}  stderr: {p.stderr.read()}")
TcpCmdError: Process is dead, returncode: -6  stdout: b'#RTS# Detected 32 CPUs: Using 32 worker threads for 1:1 mapping with CPU affinity set.\n#RTS# Using distributed database backend replication factor of 3\n#RTS# Using distributed database backend (DDB): 127.0.0.1:17400\n#RTS# Using distributed database backend (DDB): 127.0.0.1:17401\n#RTS# Using distributed database backend (DDB): 127.0.0.1:17402\n#RTS# Checking for existing actor state in DDB.\n#RTS# No previous state in DDB; Initializing database...\n#RTS# Database intialization complete.\nGot connection\nConnection from localhost\nRECV GET\nRECV \nConnection from localhost\nGot connection\nRECV INC\n'  stderr: b"ddb_test_server: backend/client_api.c:693: send_packet_wait_replies_async: Assertion `0' failed.\n"

----------------------------------------------------------------------
Ran 1 test in 0.068s

FAILED (errors=1)
make: *** [Makefile:47: test_db_app_tcp] Error 1
kll@Boxy:~/terastream/acton/test$ 
```

That function:
```c
int send_packet_wait_replies_async(void * out_buf, unsigned out_len, int64_t nonce, msg_callback ** mc, remote_db_t * db)
{
	int ret = 0;
	*mc = add_msg_callback(nonce, NULL, db);

	if(*mc == NULL)
	{
		assert(0);   // <<<<<<<< this assert

		return -1;
	}

```

how can that be, when is the message callback null?

**Comment by plajjan** [comment]
I think this has been fixed through one or more of the many fixes from @aagapi in the area of segfaults in the DB. I don't think this issue is actionable, so I'm closing it.
