### ISSUE TITLE
DB client segfault in add_reply_to_nonce

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#539]
Got another segfault that we can trace to the DB client library I think. stacktrace:

```
(gdb) bt 
#0  0x00000007f305c000 in ?? ()
#1  0x000000000048e83b in add_reply_to_nonce (reply=0x7f309801c2b0, reply_type=4, nonce=95060511178715, db=0x5d5a90) at backend/client_api.c:485
#2  0x000000000048e27a in comm_thread_loop (args=0x5d5a90) at backend/client_api.c:325
#3  0x00007f309f54beae in start_thread (arg=0x7f309f22a640) at pthread_create.c:463
#4  0x00007f309f32da5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by plajjan** [comment]
I think this has been fixed through one or more of the many fixes from @aagapi in the area of segfaults in the DB. I don't think this issue is actionable, so I'm closing it.
