### ISSUE TITLE
Run brew test & fix test

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#882]
We don't test the formula and it looks like we've got an error, see https://github.com/actonlang/homebrew-acton/actions/runs/3085975337/jobs/4989860066

```
brew test --verbose actonlang/acton/acton
==> FAILED
Full test actonlang/acton/acton output
  ==> Testing actonlang/acton/acton
  ==> /usr/local/Cellar/acton/0.11.4/bin/actonc --version
  acton 0.11.4
  compiled by ghc 8.10 on darwin x86_64
  cc: Apple clang version 13.0.0 (clang-1300.0.29.30)
  ==> ./hello
  Error: actonlang/acton/acton: failed
  An exception occurred within a child process:
    Errno::ENOENT: No such file or directory - ./hello
  /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:25:in ``'
  /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:25:in `shell_output'
  /usr/local/Homebrew/Library/Taps/actonlang/homebrew-acton/Formula/acton.rb:55:in `block in <class:Acton>'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2265:in `block (3 levels) in run_test'
  /usr/local/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2264:in `block (2 levels) in run_test'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2263:in `block in run_test'
  /usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
  /usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
  /usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2540:in `mktemp'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2257:in `run_test'
  /usr/local/Homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /usr/local/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
Warning: linkage failed, test failed
```

**Comment by plajjan** [comment]
Fixed by #883.
