### ISSUE TITLE
Unhandled NO_QUORUM_ERR in remote_commit_txn

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#959]
### Acton Version

0.11.7

### Steps to Reproduce

- run rts_db/test_tcp_client many times and wait for segfault in the "right" place...

### Expected Behavior

Not segfault...

### Actual Behavior

```c
Core was generated by `./rts_db/ddb_test_client 10979 --rts-verbose --rts-debug --rts-ddb-replication'.
Program terminated with signal SIGABRT, Aborted.

warning: Section `.reg-xstate/3500634' in core file too small.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f7fb0ff1640 (LWP 3500634))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f7fbe0895df in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f7fbe03da02 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f7fbe028469 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f7fbe028395 in __assert_fail_base (fmt=0x7f7fbe1b7cd0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x50157b "0", 
    file=0x501566 "backend/client_api.c", line=2907, function=<optimized out>) at ./assert/assert.c:92
#5  0x00007f7fbe036ab2 in __GI___assert_fail (assertion=0x50157b "0", file=0x501566 "backend/client_api.c", line=2907, 
    function=0x502590 <__PRETTY_FUNCTION__.1> "remote_commit_txn") at ./assert/assert.c:101
#6  0x00000000004acd2f in remote_commit_txn (txnid=0x7f7f9c000ce0, db=0x1227800) at backend/client_api.c:2907
#7  0x0000000000436b64 in wt_work_cb (ev=0x59d1f0 <work_ev+240>) at rts/rts.c:1379
#8  0x00000000004ccfe1 in uv.run_check ()
#9  0x00000000004ca67b in uv_run ()
#10 0x00000000004375a1 in main_loop (idx=0x2) at rts/rts.c:1490
#11 0x00000000004f7a51 in GC_inner_start_routine ()
#12 0x00000000004ea805 in GC_call_with_stack_base ()
#13 0x00007f7fbe08784a in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#14 0x00007f7fbe10b2cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) frame 6
#6  0x00000000004acd2f in remote_commit_txn (txnid=0x7f7f9c000ce0, db=0x1227800) at backend/client_api.c:2907
2907			assert(0);
(gdb) frame 6
#6  0x00000000004acd2f in remote_commit_txn (txnid=0x7f7f9c000ce0, db=0x1227800) at backend/client_api.c:2907
2907			assert(0);
(gdb) info locals
ts_start = {tv_sec = 3708312, tv_nsec = 531436830}
len = 0
tmp_out_buf = 0x0
rs = 0x12291a0
commit_stamp = 0x7f7f9c002050
val_res = -1
__PRETTY_FUNCTION__ = "remote_commit_txn"
(gdb) 

```

val_res = -1 means _remote_validate_txn must have returned -1, which means NO_QUORUM_ERR... so I think we just need to handle this error here, right?

**Comment by aagapi** [comment]
Fixed in https://github.com/actonlang/acton/pull/957
